(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'data' is not defined"
p3
sS'layer'
p4
S'G:\\realpython\\web2py\\start\\applications\\pulse\\controllers/default.py'
p5
sS'code'
p6
S"import requests\n\ndef index():\n    form = FORM(\n        TEXTAREA(_name='pulse', requires=IS_NOT_EMPTY()),\n        INPUT(_type='submit')).process()\n    if form.accepted:\n        redirect(URL('pulser', args=form.vars.pulse))\n    return dict(form=form)\n\ndef pulser():\n    text = request.args(0)\n    text = text.split('_')\n    text = ' '.join(text)\n    url = 'http://text-processing.com/api/sentiment/'\n    r = requests.post(url, data=data)\n    return dict(text=text, r=r.content)\n\nresponse._vars=response._caller(pulser)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "G:\\realpython\\web2py\\start\\gluon\\restricted.py", line 220, in restricted\n    exec ccode in environment\n  File "G:\\realpython\\web2py\\start\\applications\\pulse\\controllers/default.py", line 19, in <module>\n  File "G:\\realpython\\web2py\\start\\gluon\\globals.py", line 385, in <lambda>\n    self._caller = lambda f: f()\n  File "G:\\realpython\\web2py\\start\\applications\\pulse\\controllers/default.py", line 16, in pulser\n    r = requests.post(url, data=data)\nNameError: global name \'data\' is not defined\n'
p11
s.